name: datadebat
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.13
  - pip
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - pip:
    - attrs==25.4.0
    - certifi==2025.10.5
    - cffi==2.0.0
    - charset-normalizer==3.4.4
    - contourpy==1.3.3
    - cycler==0.12.1
    - elastic-transport==8.17.1
    - elasticsearch==8.10.0
    - fonttools==4.60.1
    - idna==3.11
    - iniconfig==2.3.0
    - kiwisolver==1.4.9
    - lxml==6.0.2
    - matplotlib==3.10.7
    - numpy==2.3.3
    - pandas==2.3.3
    - pillow==12.0.0
    - pluggy==1.6.0
    - pycparser==2.23
    - pyparsing==3.2.5
    - pytest==8.4.2
    - pytest-order==1.3.0
    - pytz==2025.2
    - pyyaml==6.0.3
    - requests==2.32.5
    - seaborn==0.13.2
    - sniffio==1.3.1
    - tqdm==4.67.1
    - tzdata==2025.2
    - urllib3==2.5.0
    - wordcloud==1.9.4
